
#include <cinttypes>
#include "masks/masks0.h"

// Masks for a single 0:
const uint64_t masks0[65] = {
  0x7FFFFFFFFFFFFFFF,0xBFFFFFFFFFFFFFFF,0xDFFFFFFFFFFFFFFF,0xEFFFFFFFFFFFFFFF,
  0xF7FFFFFFFFFFFFFF,0xFBFFFFFFFFFFFFFF,0xFDFFFFFFFFFFFFFF,0xFEFFFFFFFFFFFFFF,
  0xFF7FFFFFFFFFFFFF,0xFFBFFFFFFFFFFFFF,0xFFDFFFFFFFFFFFFF,0xFFEFFFFFFFFFFFFF,
  0xFFF7FFFFFFFFFFFF,0xFFFBFFFFFFFFFFFF,0xFFFDFFFFFFFFFFFF,0xFFFEFFFFFFFFFFFF,
  0xFFFF7FFFFFFFFFFF,0xFFFFBFFFFFFFFFFF,0xFFFFDFFFFFFFFFFF,0xFFFFEFFFFFFFFFFF,
  0xFFFFF7FFFFFFFFFF,0xFFFFFBFFFFFFFFFF,0xFFFFFDFFFFFFFFFF,0xFFFFFEFFFFFFFFFF,
  0xFFFFFF7FFFFFFFFF,0xFFFFFFBFFFFFFFFF,0xFFFFFFDFFFFFFFFF,0xFFFFFFEFFFFFFFFF,
  0xFFFFFFF7FFFFFFFF,0xFFFFFFFBFFFFFFFF,0xFFFFFFFDFFFFFFFF,0xFFFFFFFEFFFFFFFF,
  0xFFFFFFFF7FFFFFFF,0xFFFFFFFFBFFFFFFF,0xFFFFFFFFDFFFFFFF,0xFFFFFFFFEFFFFFFF,
  0xFFFFFFFFF7FFFFFF,0xFFFFFFFFFBFFFFFF,0xFFFFFFFFFDFFFFFF,0xFFFFFFFFFEFFFFFF,
  0xFFFFFFFFFF7FFFFF,0xFFFFFFFFFFBFFFFF,0xFFFFFFFFFFDFFFFF,0xFFFFFFFFFFEFFFFF,
  0xFFFFFFFFFFF7FFFF,0xFFFFFFFFFFFBFFFF,0xFFFFFFFFFFFDFFFF,0xFFFFFFFFFFFEFFFF,
  0xFFFFFFFFFFFF7FFF,0xFFFFFFFFFFFFBFFF,0xFFFFFFFFFFFFDFFF,0xFFFFFFFFFFFFEFFF,
  0xFFFFFFFFFFFFF7FF,0xFFFFFFFFFFFFFBFF,0xFFFFFFFFFFFFFDFF,0xFFFFFFFFFFFFFEFF,
  0xFFFFFFFFFFFFFF7F,0xFFFFFFFFFFFFFFBF,0xFFFFFFFFFFFFFFDF,0xFFFFFFFFFFFFFFEF,
  0xFFFFFFFFFFFFFFF7,0xFFFFFFFFFFFFFFFB,0xFFFFFFFFFFFFFFFD,0xFFFFFFFFFFFFFFFE
};

